# Generated by Django 5.0.4 on 2024-06-28 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('registration_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('num_employees', models.PositiveIntegerField(default=0, editable=False)),
                ('contact_phone', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employment_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=11, null=True)),
                ('role', models.CharField(max_length=100)),
                ('date_started_role', models.DateField()),
                ('date_left_role', models.DateField(blank=True, null=True)),
                ('duties', models.TextField()),
                ('username', models.CharField(default=0, max_length=15, unique=True)),
                ('email', models.EmailField(default='company@company.com', max_length=254, unique=True)),
                ('password', models.CharField(default='123456789123', max_length=12)),
                ('employment_status', models.BooleanField(default=True)),
                ('company_user_status', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.company')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=100)),
                ('date_started_role', models.DateField()),
                ('date_left_role', models.DateField(blank=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('employment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
