# Generated by Django 5.0.7 on 2024-07-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_company_user_employment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
