# Generated by Django 5.0.4 on 2024-06-30 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_department_employee_employeehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company_id',
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_departments',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='department', to='api.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default='', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
