# Generated by Django 5.0.4 on 2024-06-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_department_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
