# Generated by Django 5.0.7 on 2024-07-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_role_employee_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='duties',
            field=models.CharField(default='buying', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='buyer', max_length=50),
            preserve_default=False,
        ),
    ]
