# Generated by Django 5.0.7 on 2024-07-11 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_employee_duties_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default='5c1c22fe', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='api.department'),
            preserve_default=False,
        ),
    ]
