# Generated by Django 5.0.4 on 2024-07-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
    ]
