# Generated by Django 5.0.4 on 2024-07-01 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(default='d78b9562', on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='api.company'),
            preserve_default=False,
        ),
    ]
