# Generated by Django 5.0.4 on 2024-07-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment_id',
            field=models.ForeignKey(default='d78b9562', on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, default='', max_length=15, unique=True),
        ),
    ]
