# Generated by Django 5.0.7 on 2024-07-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_employeehistory_date_started_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='duties',
            field=models.CharField(max_length=50),
        ),
    ]
