# Generated by Django 5.0.7 on 2024-07-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_employeehistory_duties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='date_left_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='date_started_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
