# Generated by Django 5.0.4 on 2024-07-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_profile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employment_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_ids',
            field=models.ForeignKey(default='f7c9bb6c', on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
            preserve_default=False,
        ),
    ]
