# Generated by Django 5.0.7 on 2024-07-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_employeehistory_date_left_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='employment_id',
            field=models.CharField(max_length=8),
        ),
    ]
