# Generated by Django 5.0.7 on 2024-07-13 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_employeehistory_employment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='duties',
        ),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='department', to='api.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_left_role',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_started_role',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='duties',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='date_left_role',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='date_started_role',
            field=models.DateField(default='2024-07-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='employment_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
