# Generated by Django 5.0.4 on 2024-07-02 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_employment_ids_profile_employment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(default='d78b9562', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.company'),
            preserve_default=False,
        ),
    ]
