# Generated by Django 5.0.7 on 2024-07-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_department_employee_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeehistory',
            name='duties',
            field=models.TextField(default='damn'),
            preserve_default=False,
        ),
    ]
