# Generated by Django 5.0.7 on 2024-07-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_employeehistory_duties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_left_role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_started_role',
            field=models.CharField(max_length=100),
        ),
    ]
