# Generated by Django 5.0.7 on 2024-07-13 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_employee_date_left_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.employee'),
        ),
    ]
