# Generated by Django 5.0.7 on 2024-07-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_employment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='employment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='api.employee'),
        ),
    ]
