# Generated by Django 5.0.4 on 2024-07-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employment_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
