# Generated by Django 5.0.4 on 2024-07-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_profile_employment_id_remove_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
