# Generated by Django 5.0.7 on 2024-07-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_employeehistory_employment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_left_role',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_started_role',
            field=models.DateField(),
        ),
    ]
