# Generated by Django 5.0.4 on 2024-07-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_company_user_employment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment_id',
        ),
    ]
