# Generated by Django 5.0.4 on 2024-07-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_user_company_remove_user_employment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default='84fb917c', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='employment_id',
            field=models.ForeignKey(default='9d5dd2a2', on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
            preserve_default=False,
        ),
    ]
