# Generated by Django 5.0.4 on 2024-07-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_company_user_employment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
