# Generated by Django 5.0.4 on 2024-07-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_employee_password_remove_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='default.jpg', null=True, upload_to='company_images'),
        ),
    ]
