# Generated by Django 5.0.4 on 2024-07-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
