# Generated by Django 5.0.4 on 2024-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company_user_status',
        ),
        migrations.AddField(
            model_name='user',
            name='company_user_status',
            field=models.BooleanField(default=True),
        ),
    ]
