# Generated by Django 5.0.4 on 2024-07-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_employee_company_user_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
